package com.customerservice.customerdetails.webservice;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2016-08-17T00:35:25.661-05:00
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://webservice.customerdetails.customerservice.com/", name = "ServicePlanWS")
@XmlSeeAlso({ObjectFactory.class})
public interface ServicePlanWS {

    @WebMethod
    @RequestWrapper(localName = "getServicePlan", targetNamespace = "http://webservice.customerdetails.customerservice.com/", className = "com.customerservice.customerdetails.webservice.GetServicePlan")
    @ResponseWrapper(localName = "getServicePlanResponse", targetNamespace = "http://webservice.customerdetails.customerservice.com/", className = "com.customerservice.customerdetails.webservice.GetServicePlanResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.customerservice.customerdetails.webservice.ServicePlan> getServicePlan();
}
